In [1]:
from typing import List

from numpy import array as np_array
from numpy import ndarray as Array
from numpy import zeros


def matrix_rotation(matrix: Array, right: bool = True) -> Array:
    row: int = matrix.shape[0]
    col: int = matrix.shape[1]
    result: Array = zeros((col, row))
    if right:
        for r in range(row):
            for c in range(col):
                result[c][row - 1 - r] = matrix[r][c]
    else:
        for r in range(row):
            for c in range(col):
                result[col - 1 - c][r] = matrix[r][c]
    return result


def matrix_transposing_left(matrix: Array) -> Array:
    row: int = matrix.shape[0]
    col: int = matrix.shape[1]
    for r in range(row):
        for c in range(r, col):
            matrix[c][r], matrix[r][c] = matrix[r][c], matrix[c][r]
    return matrix


def matrix_transposing(matrix: Array) -> Array:
    row: int = matrix.shape[0]
    col: int = matrix.shape[1]
    new_c: int = col - 1
    for r in range(row):
        new_r: int = row - 1
        for c in range(col - r - 1):
            matrix[r][c], matrix[new_r][new_c] = (
                matrix[new_r][new_c],
                matrix[r][c],
            )
            new_r -= 1
        new_c -= 1
    return matrix


def matrix_rotation_inplace(matrix: Array, right: bool = True) -> Array:
    if matrix.shape[0] != matrix.shape[1]:
        return matrix_rotation(matrix, right=right)
    row: int = matrix.shape[0]
    if right:
        matrix = matrix_transposing(matrix)
    else:
        matrix = matrix_transposing_left(matrix)
    for r in range(row // 2):
        tmp = matrix[r].copy()
        matrix[r] = matrix[row - 1 - r]
        matrix[row - 1 - r] = tmp
    return matrix


arrays: List[Array] = [
    np_array([[1, 2], [3, 4]]),
    np_array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
    np_array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]),
    np_array([[1, 2], [3, 4], [5, 6], [7, 8]]),
]
for a in arrays:
    print("-" * 20)
    print(a)
    print("=" * 20)
    print(matrix_rotation_inplace(a.copy()))
    print("=" * 20)
    print(matrix_rotation_inplace(a, right=False))
    print("-" * 20)


--------------------
[[1 2]
 [3 4]]
[[3 1]
 [4 2]]
[[2 4]
 [1 3]]
--------------------
--------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]
[[3 6 9]
 [2 5 8]
 [1 4 7]]
--------------------
--------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]
[[ 4  8 12 16]
 [ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]]
--------------------
--------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[7. 5. 3. 1.]
 [8. 6. 4. 2.]]
[[2. 4. 6. 8.]
 [1. 3. 5. 7.]]
--------------------
